### ISSUE TITLE
ReadTimeoutException login error

### ISSUE THREAD

**Issue by Lammendam** [ProtocolSupport/ProtocolSupport#1140]
I'm using ProtocolSupport on my hub-server (connected to BungeeCord). When player is trying to join the server first time after server load, he can't connect to server, few seconds later he got "Disconnected" message in his client. In the console i got this:
https://pastebin.com/BCYhsuAW
Player rejoins to server again and finally all is good.

ProtocolSupport: v4.29-dev
Spigot 1.14.4 (latest build)

When i disabled "PS" this issue is gone.
Before test i use /ps debug.

**Comment by Shevchik** [comment]
Happens sometimes, will try to figure out why connection becomes stuck.

**Comment by Shevchik** [comment]
Try using the latest dev build. I fixed some race condition found by Tux, which may be related to this.

**Comment by Lammendam** [comment]
@Shevchik still the same...
I assumed that ProtocolLib might conflict with PS... but disabling PLib didn't help..

**Comment by Shevchik** [comment]
Yeah. Still happens for me. It's possible that this problem happens of something initalizing wrong first time in protocolsupport. Were you able to find out if it happens for specific client versions, or not?

**Comment by Lammendam** [comment]
At this moment, i've tested only on every sub-version of 1.14.x. I can test it in few days on earlier client versions.

**Comment by Shevchik** [comment]
Should be fixed now.

**Comment by Lammendam** [comment]
Agree.
I've tested latest dev. build and it works fine for me. Issue is gone.
