### ISSUE TITLE
Biomes below v1.15.x are Ocean && Sounds

### ISSUE THREAD

**Issue by TNTUP** [ProtocolSupport/ProtocolSupport#1202]
/version > Running on Paper 1.15.1 #\33 
/ps buildinfo > protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.01.04 at 13:35:33 MSK, buildhost: build.true-games.org, buildnumber: 467, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:a82f2b462774aee5e15680f7c1a4692e6a559517))

![image](https://user-images.githubusercontent.com/1524355/72035189-2447ea80-3265-11ea-86fa-1c3b4cd8e05f.png)

By looking at the screen, on the left side I'm on 1.12.2 on a 1.15.1 server. The biome where I am on the 1.12.2 client is in a Savanna Biome and it should not rain there! By checking F3 debug menu, it says "Ocean" which is incorrect. On the 1.15.1 client the biome is "Savanna" which is correct. I've tested 1.14.x, 1.13.x, 1.12.x and they report incorrect biome data.

Also another bug, I haven't tested all sounds but one I noticed it when a creeper exploded, I didn't hear its explosion sound but it does hiss at the player. Tried TNT aswell, I don't hear the explosion sound. 

edit: loaded up 1.13.2 and 1.14.4 (1.12.2 and 1.15.1 too from the last screen) 
![image](https://user-images.githubusercontent.com/1524355/72035621-69205100-3266-11ea-902e-59b3dc0f12b3.png)

**Comment by Shevchik** [comment]
Fixed the biomes.

Create a separate issue for sounds.

**Comment by TNTUP** [comment]
Will do and thanks for this fix :)

**Comment by MasterDash5** [comment]
Biomes still dont translate for 1.8 clients. Seems to work fine for 1.7 though.

**Comment by Shevchik** [comment]
Yeah, missed those version, should have read the TODO list >_<.
