### ISSUE TITLE
Item visual bug

### ISSUE THREAD

**Issue by ludgart** [ProtocolSupport/ProtocolSupport#1315]
Hello,

if you die with the minecraft version 1.8.9 it drop the items on the ground. But, if someone pickup the items, you still see the items on the ground. Visual bug.

Picture: https://gyazo.com/63ed5d3df9347e058e16010e5fde1c61 ( It is not possible to pickup the items, because there already picked up )

Server version: 1.16.5 - Paper-418
ProtocolSupport: 594

**Comment by Shevchik** [comment]
Huh, i'm sure i fixed something like this before.
Does this apply to self only or for other players too?

**Comment by ludgart** [comment]
Hey,

I tested it with the latest build 599. The problem is still there. I tried it with the version 1.8.9

**Comment by ludgart** [comment]
Hey,

is there any way to fix this? This happen to all players on 1.8.x.
