### ISSUE TITLE
Immediately kicked out when using the same client and server version

### ISSUE THREAD

**Issue by Doctacosa** [ProtocolSupport/ProtocolSupport#1344]
Trying to join a server with recent builds of ProtocolSupport causes my client to disconnect almost immediately with Connection Lost:

*Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(65) + length(1) exceeds writerIndex(65): PooledUnsafeDirectByteBuf(ridx: 65, widx: 65, cap: 65)*

Removing ProtocolSupport allows me to join properly. I'm getting the same problem with or without Bungee installed. All other plugins have been removed, this is using a fresh world. The client is unmodded.

Any clients using a version lower than the server, like 1.16.4, are able to connect just fine. This only happens using a 1.17.1 client on a 1.17.1 server.

Note that this isn't new to 1.17.1 either, I have been getting the same results since 1.17 using a 1.17 client. My live 1.16 install (on build 619) doesn't have this issue.

Is there a server setting somewhere that could be causing this, or did I trigger an odd issue within ProtocolSupport itself?

**ProtocolSupport version:**
[21:30:55] [Server thread/INFO]: [buildtime=2021.07.07 at 03:09:54 MSK, buildhost=https://build.true-games.org, buildnumber=635, buildgit=https://github.com/ProtocolSupport/ProtocolSupport/commit/3fbd9c9252b9a202851a4bb95834cf102143bb6a]

**Server version:**
[21:31:33] [Server thread/INFO]: This server is running CraftBukkit version 3172-Spigot-610a8c0-99561c2 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
[21:31:33] [Server thread/INFO]: Checking version, please wait...
[21:31:33] [Thread-8/INFO]: You are running the latest version

**Debug output:**
[21:28:42] [Netty Server IO #2/INFO]: [ProtocolSupport] /127.0.0.1:62251 connected with protocol version MINECRAFT_1_17_1
[21:28:42] [LoginProcessingThread/INFO]: UUID of player Doctacosa is 5c0b6869-6892-4321-bac6-3c02105f6d5a
[21:28:43] [Server thread/INFO]: Doctacosa[/127.0.0.1:62251] logged in with entity id 90 at ([world]-95.5, 4.0, -207.5)
[21:28:43] [Server thread/INFO]: Doctacosa lost connection: Disconnected
[21:28:43] [Server thread/INFO]: Doctacosa left the game
[21:28:46] [Netty Server IO #3/INFO]: [ProtocolSupport] /127.0.0.1:62257 connected with protocol version MINECRAFT_1_17_1

Thanks!

**Comment by Shevchik** [comment]
Yes, most likely some packet encoding is wrong. Follow the instructions provided on https://wiki.vg/Debugging to enable network packets log and paste a resulting packet log.

**Comment by Doctacosa** [comment]
Here's the server network packets log, including a join attempt that replicates the issue.
[server.log](https://github.com/ProtocolSupport/ProtocolSupport/files/6778400/server.log)

**Comment by Shevchik** [comment]
I also need a client log with debugging enabled, since the server log will contain a lot of packets that weren't processed yet by the client, so it's hard to figure out which one exactly caused the issue.

**Comment by Doctacosa** [comment]
Got it.

Is there a specific trick to enable these logs in the client? I've used the same parameter as with the server, but I just get the regular output instead of the packets. The linked documentation doesn't mention if the newer launcher handles that differently.
![image](https://user-images.githubusercontent.com/48997592/124792040-9fea2c80-df1a-11eb-84aa-621b5da3c887.png)

**Comment by Shevchik** [comment]
Yeah, the official launcher does silently override log configuration. The only workaround for the official launcher would be creating a copy of the game version json manually and removing the logging section.

**Comment by Shevchik** [comment]
Btw, can you also try disabling resource pack, i didn't test it on 1.17 yet, but maybe it is the thing that is breaking.

**Comment by Doctacosa** [comment]
That's a significant gotcha on client logs, but that's how this game goes sometimes! Here's the client log with the matching one server-side.
[client.log](https://github.com/ProtocolSupport/ProtocolSupport/files/6778831/client.log)
[server.log](https://github.com/ProtocolSupport/ProtocolSupport/files/6778834/server.log)

Your hunch on resource pack is correct! Removing the file reference in server.properties clears up the error and allows me to join properly. I'm not sure if that plays a role, but the pack itself hasn't been updated to the latest version yet.

**Comment by Shevchik** [comment]
Should probably be fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/cd16167c0a6ee675ccb47e792940a1e3d70a379a
Did test it, but since it was missing the forced text write, i guess that should be the reason.

**Comment by Doctacosa** [comment]
Thanks for the quick replies!

That had an effect, but doesn't quite solve it as I'm getting a different error from before.

*Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: index: 67, length: 123 (expected: range(0, 77))*

New logs:
[client.log](https://github.com/ProtocolSupport/ProtocolSupport/files/6780519/client.log)
[server.log](https://github.com/ProtocolSupport/ProtocolSupport/files/6780521/server.log)

Removing the resource pack in server.properties works, as before.

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/786eb76badb7f5700b1bad47a5d0e3a0684fef23
This time i tested it and it works.

**Comment by Doctacosa** [comment]
Confirmed, this passed my own battery of tests.

Thanks for the help, much appreciated!
