### ISSUE TITLE
Shulker Boxes that are opened in 1.10 never close again

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#321]
When you open a shulker box in 1.10 it will stay open and never close again until the containing chunk is reloaded by the server.

on 1.11 it may be visually closed until you try to open it, but the serverside collision box is always the size of the open shulker box

**Comment by Shevchik** [comment]
Should be fixed now, shulker box will now properly open for all versions.

**Comment by Brokkonaut** [comment]
They still don't close when opened in 1.10 or older. The shulker box stays at 1.5 blocks collision box size on the server side

**Comment by Shevchik** [comment]
Unable to reproduce, need exact reproduction steps.

**Comment by Brokkonaut** [comment]
It is fixed now, since the change from stone to workbenches as replacement
