### ISSUE TITLE
java.lang.NoSuchMethodError When Enchanting

### ISSUE THREAD

**Issue by Proplex** [ProtocolSupport/ProtocolSupport#339]
Hey there, just note that this is different than the enchanting error that was fixed in #646.

When players place items in enchanting tables, the error "Limited Enchantability" appears on their GUI. The item still enchants, but there is no message hinting towards what enchant it would be.

http://pastebin.com/raw/QQrEe6RL

Spigot recently changed in a commit the PrepareItemEnchantEvent instantiation to now require an EnchantmentOffer https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/enchantment/PrepareItemEnchantEvent.html

**Comment by Shevchik** [comment]
Yeah, but it will take time to fix this one bug.

**Comment by helptiger** [comment]
additional error log

http://pastebin.com/WDtSb4pe

**Comment by Shevchik** [comment]
Okay, so i was right about spigot code being wrong. Will fix it soon.

**Comment by Shevchik** [comment]
Should be fixed now, but i actually think about removing enchant table injection, and instead adding a separate plugin that autoadds lapis from player inventory on enchanting open.

**Comment by delsolsi** [comment]
Issue still persist on the dev build #648 http://pastebin.com/aMWEXr69

**Comment by Proplex** [comment]
Yep, it's all good now with the latest spigot build. Thanks a lot!

**Comment by Proplex** [comment]
@luis, what build of Spigot are you using? EnchantmentOffer was added a
week or two ago. Try updating your Spigot build and see if that works.

*David Lohle*
GLADOS Software Developer | (718) 734-7598
University at Buffalo Nanosatellite Laboratory
