### ISSUE TITLE
Tile entity data packet does not work

### ISSUE THREAD

**Issue by WesJD** [ProtocolSupport/ProtocolSupport#460]
When sending `PacketPlayOutTileEntityData`, in my case setting sign text, no change occurs for the client. I am using ProtocolLib v4.2.1 and ProtocolSupport v4.25. This issue does not occur when ProtocolSupport is not installed.

**Comment by Shevchik** [comment]
Post the code that you use to send data.

**Comment by WesJD** [comment]
@Shevchik 
```java
public SignPrompt(Player player, String prompt, Consumer<List<String>> response) {
        try {
            final Location location = player.getLocation();
            location.setY(255);
            player.sendBlockChange(location, Material.SIGN_POST, (byte) 0);

            final BlockPosition position = new BlockPosition(location.toVector());

            final PacketContainer openSign = new PacketContainer(PacketType.Play.Server.OPEN_SIGN_ENTITY);
            openSign.getBlockPositionModifier().write(0, position);
            PROTOCOL_MANAGER.sendServerPacket(player, openSign);

            final PacketContainer writeToSign = new PacketContainer(PacketType.Play.Server.TILE_ENTITY_DATA);
            writeToSign.getBlockPositionModifier().write(0, position);
            writeToSign.getIntegers().write(0, 9);
            final NbtCompound compound = NbtFactory.ofCompound("");
            final List<String> lines = getLines(prompt);
            for(int i=0; i < 4; i++) compound.put("Text" + (i + 1), "{\"text\":\"" + (lines.size() > i ? lines.get(i) : "") + "\"}");
            writeToSign.getNbtModifier().write(0, compound);
            PROTOCOL_MANAGER.sendServerPacket(player, writeToSign);

            PROTOCOL_MANAGER.addPacketListener(new PacketAdapter(Keypads.get(), PacketType.Play.Client.UPDATE_SIGN) {
                @Override
                public void onPacketReceiving(PacketEvent event) {
                    if(event.getPlayer().getUniqueId().equals(player.getUniqueId())) {
                        final PacketContainer container = event.getPacket();

                        response.accept(Arrays.asList(container.getStringArrays().read(0)));

                        PROTOCOL_MANAGER.removePacketListener(this);
                        player.sendBlockChange(location, Material.AIR, (byte) 0);
                    }
                }
            });
        } catch (InvocationTargetException ex) {
            ex.printStackTrace();
        }
    }
```

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by WesJD** [comment]
Unfortunately it's still not working with the latest build (#43).

**Comment by Shevchik** [comment]
Should work now
