### ISSUE TITLE
1.12.1 client on 1.12.2 server: Sometimes I get "Ping timeout" immediately

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#696]
Sometimes I get kicked with "Ping timeout" immediately when i join a 1.12.2 server with 1.12.1 (or older) clients.

**Comment by MylesIsCool** [comment]
It's worth noting the vanilla server only stores the last sent keep alive

**Comment by Shevchik** [comment]
^

**Comment by FlamestoN** [comment]
Same issue, in most cases give kick with "Timeout" ...

**Comment by Shevchik** [comment]
Make sure that you don't have any plugins that might send or receive keep alive packets

**Comment by FlamestoN** [comment]
Without bungeecord, everything is fine.
With bungeecord often gives kick with "Time out"

**Comment by FlamestoN** [comment]
Without bungeecord everything is fine

**Comment by UberMC** [comment]
I can recreate this by connecting using a VPN set to Europe (From Canada) server in USA.
1.8.8 ->Disconnected
1.12 ->Timed out

or using my linux laptop on wifi
1.12 Timed out

Only happens on my creative server though not skyblock.

**Comment by UberMC** [comment]
Also  Spigot pushed this. Which seems related 
https://hub.spigotmc.org/jira/browse/SPIGOT-3571
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/94b098085269b86ae8f926fe64e06fa3fbe6a7ca

But doesn't solve the issue. (It stopped some glitchy behavior with player entities though)

**Comment by FlamestoN** [comment]
Sorry for the false information, this problem also occurs on the server without bungeecord.
But for some reason, this error disappears if the player enters the server with an empty world (no blocks) and view-distance 4 or lower

**Comment by Shevchik** [comment]
Do a packet log, and post it here

**Comment by FlamestoN** [comment]
[packet log](https://pastebin.com/rJPqS1Yz)

**Comment by UberMC** [comment]
Appears to be something in the world causing this.

**Comment by UberMC** [comment]
I deleted my data folder and it fixed it

**Comment by i9hdkill** [comment]
You sure? Can anyone confirm that this is helping?

**Comment by FlamestoN** [comment]
No, this is not a problem of peace.
I'm using the latest kernel, the latest protocolsupport and last protocolib and the new generated world, still have this problem.

You can test on my test server: 193.70.7.5:38855

**Comment by UberMC** [comment]
**Solution (But not recommended)**
-Delete the world's data folder.

**How I came to this resolution**

**Recreating Timeout issue**
I can recreate this by connecting using a VPN set to Europe (From Canada) server in USA.
1.8.8 ->Disconnected
1.12 ->Timed out

or using my linux laptop on wifi
1.12 Timed out

**My process of elimination**
Removing all plugins didn't help
Change native transport didn't help
Deleting all regions in the world didn't help
Deleting the data folder helped

**Early Findings to my solution**
-Player count went up 2x
-couldn't reproduce the issue with my linux laptop on wifi
-using the VPN i got a timeout about 5% of the time vs 75%

**I'm running a creative server so the data folder didn't matter much.**
**I'm not responsible for any issues with your server if you do this, it helped me and might not help you...**

**Comment by Shevchik** [comment]
Server never ever sent a keepalive in this case

**Comment by UberMC** [comment]
Is it possible to increase the 15 seconds to something higher?

**Comment by Shevchik** [comment]
It's not about 15 seconds, it's about 15 seconds not being 15 seconds after player world join.

**Comment by Shevchik** [comment]
The only one things that i can think of, is that something modifies playerconnection g, f, h fields, so try without other plugins too.

**Comment by UberMC** [comment]
So why does ProtocolSupport Disconnect after 15 seconds, where as viaversion doesn't.

**Comment by FlamestoN** [comment]
This error occurs on the server without plugins, only protocol support

**Comment by Shevchik** [comment]
ViaVersion runs on older server, which doesn't have this strange new keepalive logic.

**Comment by 7kasper** [comment]
Perhaps we should compare packet logs of a 1.12.1 and 1.12.2 player..

**Comment by Shevchik** [comment]
They don't really matter in this case, because server never sends keepalive, so it sohuld be something else.

**Comment by 7kasper** [comment]
@FlamestoN Idk about you, but I cannot connect with 1.12.2 either. Gives me timeouts aswell (on your server)

**Comment by FlamestoN** [comment]
@7kasper check now, I tried to send keep alive packets using the plugin, and to delay packets. It did not help

**Comment by Shevchik** [comment]
You can't just send keepalives by a plugin, server has to send it, or you will make everything worse, because server will disconnect you on invalid keepalive id receive.

**Comment by FlamestoN** [comment]
@Shevchik, on localhost this problem occurs less ofte, maybe because lower ping. 
You can try reproduce this, this is the server with new 1.12.2 world and last spigot http://play.craftix.ru/server.zip

**Comment by UberMC** [comment]
Removing the data folder solved my timeout issue, however if connects take longer then 15 second it disconnects.

**Comment by FlamestoN** [comment]
@UberMC I created a new world without the data folder and this problem still occurs

**Comment by UberMC** [comment]
Are connects taking longer then 15 seconds? or does it connect before 15 seconds and then d/c.

**Comment by FlamestoN** [comment]
Before 15 seconds. Connection takes 3-5 seconds

**Comment by Brokkonaut** [comment]
I get this timeout after a very few seconds (1-3 sec)

**Comment by FlamestoN** [comment]
I think this is something with the new client or the new spigot, because this problem only occurs with the protocolsupport plugin, and the client version < 1.12.2

**Comment by Shevchik** [comment]
If your connection takes longer then 15 secs, then it's logical that you have a disconnect, we are talking about instant disconnects on login here.

**Comment by FlamestoN** [comment]
@Shevchik [here](https://pastebin.com/DeV23Tb9).
Maybe this error occurs because the server 1.12.2 reads and sends keep alive in the long data type, and clients lower 1.12.2 send it in int data type?

**Comment by 7kasper** [comment]
@FlamestoN That was the original problem, but since PS caches the keepalive id now, that's not the cause.

**Comment by Shevchik** [comment]
I was finally somewhat able to reproduce the problem, will try to find out what exactly goes wrong.

**Comment by Shevchik** [comment]
Found out the problem, will fix/workaround it soon

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by Brokkonaut** [comment]
thank you 👍

**Comment by ksrawlot** [comment]
what was the solution by just saying its fixed problem was not fixed....

**Comment by Brokkonaut** [comment]
It should be fixed since https://github.com/ProtocolSupport/ProtocolSupport/commit/2259c76763b4cc557f9ff50283d892a659ad1ae5 At least on our server I had no more problems with unexpected ping timeouts any more.
