### ISSUE TITLE
ProtocolSupport-mcpeinventory/ProtocolSupport-mcpenew Compiling

### ISSUE THREAD

**Issue by GoNotCougsWA** [ProtocolSupport/ProtocolSupport#751]
Hey, I am having a really problem with Compiling All the MCPEs ProtocalSupport trees.

I am using Windows: Java 8 Update 151 (64-bit) with JDK 8 Update 151 (64-bit).

This might be a problem with gradlew but I am getting error about org.apache.http.client.ClientProtocolException with Compiling.

"FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':updateLibs'.
> org.apache.http.client.ClientProtocolException: Resource does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED
"

Also, if you get this fixed. For me in the README.md can you put in how to compile it?

**Comment by AlexCreeper25** [comment]
seems to be happening to me too

**Comment by 7kasper** [comment]
This is because the glowstone repo is down. It has bern reported so hopefully it will be fixed soon.

**Comment by AlexCreeper25** [comment]
Ok, thanks for telling us

**Comment by GoNotCougsWA** [comment]
Just saying, I have found out if you have java 9 it will not even work.

**Comment by MrPowerGamerBR** [comment]
Well, you are complaining about a pre-pre-pre-pre-pre-pre-pre alpha branch, we know it is unstable.

It isn't compiling because Glowstone's Maven repo is down.

**Comment by GoNotCougsWA** [comment]
I don't think you read the forum I created right.

**Comment by MrPowerGamerBR** [comment]
Yes I did, the first issue you said is an issue within the Glowstone repo, it is unstable and can't find the Glowstone artifacts.

About your second comment, nobody on the PSPE team is testing against Java 9 (as far as I know), we are testing against Java 8, and, again, PSPE isn't stable and we aren't accepting issues reports at the moment, because it is meant for developers.

**Comment by GoNotCougsWA** [comment]
**Just saying**, I feel like you should at least be helpful about this. This is a pre-pre-pre-pre-pre-pre-pre alpha branch. Now me, I know how to make spigot plugins. I have never done any compiling with gradlew. As for me, If something was meant for developers that said in on the info of the branch. But I am not you. This is your plugin. -.-

**Comment by MrPowerGamerBR** [comment]
`gradlew build` 🙄

And the issue you reported on this ticket was already known on ProtocolSupport's Discord server.

By the way:

![https://i.imgur.com/6CS0SmE.png](https://i.imgur.com/6CS0SmE.png)

Right in the README is says it isn't stable for public use (Work in Progress)

Also, this isn't my plugin...

**Comment by GoNotCougsWA** [comment]
Werid thing is that github says this is your plugin. 

Anyway, 
It says "WIP" means Work in progress. It don't says not for public use if you say anything you will get a bad message.

**Comment by momothereal** [comment]
The Maven repository should be fixed. Unfortunately, we lost all of our snapshot artifacts while upgrading Archiva. The version ProtocolSupport uses (`2017.11.0-SNAPSHOT`) doesn't exist anymore, so it should be updated to the latest (`2018.0.0-SNAPSHOT`).

Please inform us if this works. Sorry again for the inconvenience and the delay to fix this.

**Comment by GoNotCougsWA** [comment]
Thanks for the reply. :) I will inform you if this works.

**Comment by GoNotCougsWA** [comment]
@momothereal, I still have the same error. Something is wrong with getting some Resource does not exist.
if you want the error with --info here:
https://pastebin.com/raw/E96MB8dq

**Comment by momothereal** [comment]
@GoNotCougsWA Did you update your gradle script to target Glowstone 2018.0.0-SNAPSHOT?

**Comment by GoNotCougsWA** [comment]
@momothereal, Yes, Just to my sure that I am doing it right, do you put that link in the build.gradle? I put the 2017.11.0-SNAPSHOT link to your new one.

**Comment by momothereal** [comment]
Yes, this line should be changed:

https://github.com/ProtocolSupport/ProtocolSupport/blob/31073a6b4161d8fa6dfe8aa7919910f4ff464d55/build.gradle#L42

(and in other branches, that is)

**Comment by GoNotCougsWA** [comment]
Ok!

**Comment by GoNotCougsWA** [comment]
Ok, I had time to to able to compile
I got a ':compileJava error'
I guess there is a lot missing in the GlowStone jar.

Here the list: https://pastebin.com/raw/ijF9DhBp

I hope it just fine with fixing error.

**Comment by momothereal** [comment]
These classes are present inside the latest JARs. I'm not sure what the problem is, but I'm guessing the JAR is not being imported correctly. There might be something wrong with your build script.

**Comment by MrPowerGamerBR** [comment]
Merge `master` to the PE branch and it should work, Shevchik fixed it because my "fix" had one key thing missing... I forgot to change the JAR name to use the new artifact.

**Comment by GoNotCougsWA** [comment]
@MrPowerGamerBR Ok! Thanks. :)

**Comment by GoNotCougsWA** [comment]
Ok, I now complied it, I am now missing only a GlowStonePacketFactory.java

**Comment by GoNotCougsWA** [comment]
I don't know why this are still missing.
