### ISSUE TITLE
[1.7.X] Broken JSON Item Hover

### ISSUE THREAD

**Issue by MrPowerGamerBR** [ProtocolSupport/ProtocolSupport#77]
**In 1.8.8:**
![1.8.8 bug](http://i.imgur.com/PMrCNdz.png)
**In 1.7.2:**
![1.7.2 bug](http://i.imgur.com/m325yau.png)

Using Spigot ChatComponent API.

I use this code to create a hoverable item for the ChatComponent API:
```
`	public static String convertItemStackToJsonRegular(org.bukkit.inventory.ItemStack itemStack) {
		// First we convert the item stack into an NMS itemstack
		net.minecraft.server.v1_8_R3.ItemStack nmsItemStack = CraftItemStack.asNMSCopy(itemStack);
		NBTTagCompound compound = new NBTTagCompound();
		compound = nmsItemStack.save(compound);

		return compound.toString();
	}
```

Here is how I'm setting the JSON
```
TextComponent tc = new TextComponent(TextComponent.fromLegacyText("§b" + match.group(0) + "§f"));

						ItemStack is = new ItemStack(Material.STONE);
						ItemMeta im = is.getItemMeta();

						String title = element.html().replace("&amp;", "&");
						im.setDisplayName("§e§l" + title + " §a(" + (System.currentTimeMillis() - ms) + "ms)");
						is.setItemMeta(im);
						itemHover = new BaseComponent[]{
								new TextComponent(SparklyUtils.convertItemStackToJsonRegular(is))
						};
						tc.setHoverEvent(new HoverEvent(Action.SHOW_ITEM, itemHover));
						tc.setClickEvent(new ClickEvent(net.md_5.bungee.api.chat.ClickEvent.Action.OPEN_URL, match.group(0)));
```

**UPDATE 1:** This DOESN'T affect the JSON Click Event.

**Comment by MrPowerGamerBR** [comment]
Maybe this issue is related to #71 ?

**Comment by Shevchik** [comment]
Probably should be fixed now.

**Comment by MrPowerGamerBR** [comment]
@Shevchik sadly, it isn't :cry: 

![1.7 JSON Bug](http://i.imgur.com/9hGXCkH.png)

**Comment by MrPowerGamerBR** [comment]
@Shevchik Maybe I have a clue of why it is breaking:

Isn't JSON hover event in 1.8 uses the new block name system (minecraft:stone) and 1.7 still uses IDs (1) for JSON messages?

I think it is needed to convert the items in a JSON formatted text to the ID of it.

**Comment by MrPowerGamerBR** [comment]
I think I was right, look at the protocol specification of the JSON chat: http://wiki.vg/Chat

They still use IDs, but, if you see the revision date, it was waaaay before the 1.8 release date, so that page refers to the 1.7.X protocol.

And, if you view here: http://www.minecraftforum.net/forums/minecraft-discussion/redstone-discussion-and/351959-1-8-raw-json-text-examples-for-tellraw-title-books (in the show_item section) they use the new Minecraft 1.8 IDs.

**Comment by Shevchik** [comment]
Damn, forgot about that shit, i was testing only simple hover/click action json

**Comment by MrPowerGamerBR** [comment]
@Shevchik maybe this will help you :smile: :
```
MinecraftKey mk = new MinecraftKey(minecraftID);
ItemStack item = CraftItemStack.asNewCraftStack(Item.REGISTRY.get(mk));
Material mat = item.getType();
```
(From https://www.spigotmc.org/threads/getting-bukkit-material-from-minecraft-item-id.56684/)

This will allow you to transform a "minecraft:stone", "minecraft:red_flower", etc to a Bukkit Material, and, from a Bukkit Material, you can get the Item ID.

The problem will be parsing the JSON so you can get the Minecraft 1.8 ID to a Minecraft 1.7 ID.

Here is a JSON message with a hover event:
```
`{"extra":[{"extra":["",{"extra":[{"color":"dark_gray","text":"["},{"color":"aqua","bold":true,"text":"Dono"},{"color":"dark_gray","text":"] "}],"text":""},{"extra":[{"color":"gold","bold":true,"text":"MrPower"},{"color":"dark_red","bold":true,"text":"Gamer"},{"color":"dark_gray","bold":true,"text":"BR"}],"text":""},{"extra":[" ",{"color":"gold","text":"➤ "}],"text":""},{"extra":["",{"extra":[{"color":"aqua","clickEvent":{"action":"open_url","value":"https://www.reddit.com/r/Android/comments/3rx5hp/why_arent_all_phones_water_resistant_now/§f"},"text":"https://www.reddit.com/r/Android/comments/3rx5hp/why_arent_all_phones_water_resistant_now/§f"}],"clickEvent":{"action":"open_url","value":"https://www.reddit.com/r/Android/comments/3rx5hp/why_arent_all_phones_water_resistant_now/"},"hoverEvent":{"action":"show_item","value":["{id:\"minecraft:stone\",Count:1b,tag:{display:{Name:\"§e§lWhy aren\u0027t all phones water res... §a(1474ms)\"}},Damage:0s}"]},"text":""},{"extra":[""],"text":""}],"text":""}],"text":""}],"text":""}
```

**Comment by MrPowerGamerBR** [comment]
Also, not really related to this issue, but it seems that the c7f0522f09dbe55161281eae6fa648e42cb3b8b8 commit fixed a issue that I was having with JSON messages, where in 1.7 clients the message would be "cutted" out randomly (Example: In 1.8 the message shows as "[Owner] MrPowerGamerBR > Hello everyone! Testing 123456789" but in 1.7 it would randomly shows as "[Owner] MrPowerGamerBR >" ) depending on the length of the message, so... yay?

**Comment by Shevchik** [comment]
Should be really fixed now

**Comment by MrPowerGamerBR** [comment]
It seems to be fixed, I tested with a simple hover event using ItemStacks and did work...

Strangely, my code that I was using as a example stills shows "Invalid Item!" and shows correctly on 1.8, I will investigate this futher.

**Comment by MrPowerGamerBR** [comment]
@Shevchik found the issue.

Here is the code which causes the issue:
```
Player p = (Player) arg0;
TextComponent textComponentBase = new TextComponent(TextComponent.fromLegacyText("TextComponent "));
TextComponent textComponentHover = new TextComponent(TextComponent.fromLegacyText("Text with Hover"));

ItemStack is = new ItemStack(Material.STONE);
			
BaseComponent[] hoverItem = new BaseComponent[]{
	new TextComponent(SparklyUtils.convertItemStackToJsonRegular(is))
};
textComponentHover.setHoverEvent(new HoverEvent(Action.SHOW_ITEM, hoverItem));
			
textComponentBase.addExtra(textComponentHover);
p.spigot().sendMessage(textComponentBase);
```
**In 1.8:**
![Hover](http://i.imgur.com/21uSEeU.png)
**In 1.7:**
![Hover](http://i.imgur.com/QcZSpCb.png)

This same code doesn't cause an issue in Protocol Hack, the issue only happens when you "add a TextComponent to a existing TextComponent", which is essential when you are manipulating JSON with the ChatComponent API.

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by MrPowerGamerBR** [comment]
@Shevchik still not working :disappointed: 

I'm testing using the code I shared above, it shows correctly on 1.8, however it is broken on 1.7.

**Comment by MrPowerGamerBR** [comment]
(Still isn't fixed in the latest dev build, just commenting so you don't need to wait me to say if it is fixed or not)

**Comment by MrPowerGamerBR** [comment]
Inspected the code a little further...
```
HoverEvent event = component.getHoverEvent();
```
returns null, even when a HoverEvent exists in the component.

**Comment by MrPowerGamerBR** [comment]
Yeah, now I know what needs to be altered to the JSON so they can be displayed on 1.7.X clients.

The JSON needs to be altered from this:
```
id:\"minecraft:stone\"
```

to this:
```
id:1
```
(Without quotes!)

Even a simple RegEx match and replace would work (no, it isn't the best solution)

**Comment by Shevchik** [comment]
RegEx won't work here, this can be a part of normal message after all.
Probably will use simple json parser for it, it will allow me to walk componenets without a problems like that.

**Comment by MrPowerGamerBR** [comment]
@Shevchik that's why I said that it wasn't the best solution. :smile: 

The best way would be parsing the JSON message, doing a for with all elements (until you find a id: string), remove that id and string and replace with a id and integer.

**Comment by Shevchik** [comment]
Well, now it should work.

**Comment by MrPowerGamerBR** [comment]
@Shevchik nope :cry: 

Console:
```
[12:11:58 ERROR]: java.lang.ClassCastException: com.google.gson.JsonArray cannot
 be cast to com.google.gson.JsonPrimitive
```

Minecraft:
![Error](http://i.imgur.com/CPl3heZ.png)

**Comment by Shevchik** [comment]
Full stacktrace?

**Comment by MrPowerGamerBR** [comment]
@Shevchik that IS the Full Stacktrace.

```
[12:09:32] [Server thread/INFO]: MrPowerGamerBR[/127.0.0.1:2322] logged in with entity id 313 at ([world]-73.459755455591, 76.0, -151.48647789092763)
[12:09:36] [Thread-29/INFO]: [0;30;1m[[0;32;1m[21m✔[0;30;1m] [0;36;1mMrPowerGamerBR[m
[12:09:36] [Netty Server IO #2/ERROR]: java.lang.ClassCastException: com.google.gson.JsonArray cannot be cast to com.google.gson.JsonPrimitive
[12:09:36] [Server thread/INFO]: MrPowerGamerBR lost connection: Disconnected
[12:09:37] [Server thread/INFO]: MrPowerGamerBR left the game.
```

And no, there isn't anything in the Minecraft Launcher log. :neutral_face:

**Comment by MrPowerGamerBR** [comment]
@Shevchik I'm dumb, I forgot to turn on "/ps debug":

```
[15:06:36 WARN]: java.lang.ClassCastException: com.google.gson.JsonArray cannot
be cast to com.google.gson.JsonPrimitive
[15:06:36 WARN]:        at com.google.gson.JsonObject.getAsJsonPrimitive(JsonObj
ect.java:162)
[15:06:36 WARN]:        at protocolsupport.utils.chat.HoverActionSerializer.dese
rialize(HoverActionSerializer.java:25)
[15:06:36 WARN]:        at protocolsupport.utils.chat.HoverActionSerializer.dese
rialize(HoverActionSerializer.java:15)
[15:06:36 WARN]:        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.
java:58)
[15:06:36 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:803)
[15:06:36 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:868)
[15:06:36 WARN]:        at com.google.gson.Gson$1.deserialize(Gson.java:126)
[15:06:36 WARN]:        at protocolsupport.utils.chat.ComponentSerializer.deseri
alize(ComponentSerializer.java:96)
[15:06:36 WARN]:        at protocolsupport.utils.chat.ComponentSerializer.deseri
alize(ComponentSerializer.java:88)
[15:06:36 WARN]:        at protocolsupport.utils.chat.ComponentSerializer.deseri
alize(ComponentSerializer.java:88)
[15:06:36 WARN]:        at protocolsupport.utils.chat.ComponentSerializer.deseri
alize(ComponentSerializer.java:88)
[15:06:36 WARN]:        at protocolsupport.utils.chat.ComponentSerializer.deseri
alize(ComponentSerializer.java:26)
[15:06:36 WARN]:        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.
java:58)
[15:06:36 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:803)
[15:06:36 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:768)
[15:06:36 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:717)
[15:06:36 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:689)
[15:06:36 WARN]:        at protocolsupport.api.chat.ChatAPI.fromJSON(ChatAPI.jav
a:31)
[15:06:36 WARN]:        at protocolsupport.protocol.transformer.v_1_7.utils.Chat
JsonConverter.convert(ChatJsonConverter.java:17)
[15:06:36 WARN]:        at protocolsupport.protocol.transformer.v_1_7.clientboun
dtransformer.PlayPacketTransformer.tranform(PlayPacketTransformer.java:86)
[15:06:36 WARN]:        at protocolsupport.protocol.transformer.v_1_7.clientboun
dtransformer.PacketEncoder.encode(PacketEncoder.java:61)
[15:06:36 WARN]:        at protocolsupport.protocol.core.wrapped.WrappedEncoder.
encode(WrappedEncoder.java:30)
[15:06:36 WARN]:        at protocolsupport.protocol.core.wrapped.WrappedEncoder.
encode(WrappedEncoder.java:13)
[15:06:36 WARN]:        at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown
Source)
[15:06:36 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[15:06:36 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[15:06:36 WARN]:        at com.comphenix.protocol.reflect.accessors.DefaultMetho
dAccessor.invoke(DefaultMethodAccessor.java:16)
[15:06:36 WARN]:        at com.comphenix.protocol.compat.netty.independent.Netty
ChannelInjector.encode(NettyChannelInjector.java:520)
[15:06:36 WARN]:        at com.comphenix.protocol.compat.netty.independent.Netty
ChannelInjector$3.encode(NettyChannelInjector.java:265)
[15:06:36 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(Mes
sageToByteEncoder.java:107)
[15:06:36 WARN]:        at com.comphenix.protocol.compat.netty.independent.Netty
ChannelInjector$3.write(NettyChannelInjector.java:271)
[15:06:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invoke
Write(AbstractChannelHandlerContext.java:658)
[15:06:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(
AbstractChannelHandlerContext.java:716)
[15:06:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeA
ndFlush(AbstractChannelHandlerContext.java:706)
[15:06:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeA
ndFlush(AbstractChannelHandlerContext.java:741)
[15:06:36 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush
(DefaultChannelPipeline.java:895)
[15:06:36 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(Abstra
ctChannel.java:240)
[15:06:36 WARN]:        at com.comphenix.protocol.compat.netty.independent.Netty
ChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[15:06:36 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(Net
workManager.java:198)
[15:06:36 WARN]:        at com.comphenix.protocol.compat.netty.independent.Netty
ChannelInjector$6$3.run(NettyChannelInjector.java:375)
[15:06:36 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.ru
nAllTasks(SingleThreadEventExecutor.java:380)
[15:06:36 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.ja
va:357)
[15:06:36 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.
run(SingleThreadEventExecutor.java:116)
[15:06:36 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:06:36 ERROR]: java.lang.ClassCastException: com.google.gson.JsonArray cannot
 be cast to com.google.gson.JsonPrimitive
```

**Comment by Shevchik** [comment]
Damn, forgot that spigot chat components serialize events as json arrays.

**Comment by Shevchik** [comment]
Should work now

**Comment by MrPowerGamerBR** [comment]
@Shevchik, now you can celebrate! :tada: :tada: :tada: 

![That's a fancy screenshot, right?](http://i.imgur.com/QDcf1mI.png)

Thanks for fixing this bug! (And fixing it, because this is a "meh, not game breaking bug") :smile:
