### ISSUE TITLE
1.5.2 Clinet Have Respawn Problem

### ISSUE THREAD

**Issue by swan201** [ProtocolSupport/ProtocolSupport#92]
Sometimes 1.5.2 Clinet User die and cant respawn. if player die he click Respawn Button. but he cant respawn. but i cant get Error log.

**Comment by Shevchik** [comment]
Don't know what exactly causes it, couldn't ever reproduce this, but still get reports from players sometimes.

**Comment by swan201** [comment]
Cause is Player health is lie 0.99. So it can't Respawn. 

I cant Get Protocollib Log know.. So If you have a time. come to summerserver.ptcs.kr plz.

**Comment by Shevchik** [comment]
Lol, forgot that i'm just converting float to integer instead of ceiling it.

**Comment by Shevchik** [comment]
Should be fixed now, check it

**Comment by swan201** [comment]
Ok, I Will Check It later. If Fix it Close This issue. Thx

**Comment by swan201** [comment]
@Shevchik That Bugs its still not Fixed ;.;. Still Many People have 0.99 health. if you see go to Jonge.kr Server. That admin make 0.99 Health Check Skript. He said still many People detected 0.99 Health

**Comment by Shevchik** [comment]
They may still have, but they should not see that they are dead anymore.

**Comment by swan201** [comment]
@Shevchik Thank You! :)
